services:
  web74:
    image: webdevops/php-apache:7.4
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/app
      - ./php.ini:/opt/docker/etc/php/php.ini
      - ./db.ini:/var/secrets/db.ini
    build: .
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:oracle
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
