name: dev
services:
  web:
    container_name: php83
    image: webdevops/php-apache:8.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/app
      - ./php.ini:/opt/docker/etc/php/php.ini
      - ./logs/apache:/var/log/apache2
    build: .
    networks:
      - app-network
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:oracle
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
